# DO NOT EDIT. Configuration generated by usc
export ZSH="$HOME/.oh-my-zsh"
export ZSH_THEME="robbyrussell"
export plugin="(git vi-mode)"
source $ZSH/oh-my-zsh.sh
source ~/.local/bin/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.local/bin/zsh-autosuggestions/zsh-autosuggestions.zsh
source <(ng completion script)
alias l='ls -l'
alias ll='ls -latrh'
alias record='asciinema rec'
alias em='emacs -Q -nw'
alias ada='gnatmake'
alias vsc='code .'
alias g='git'
alias ga='git add -A'
alias gs='ga;gc;gp'
alias gcl='git clone'
alias n='npm'
alias pn='pnpm'
alias e='ls -t --color=auto --group-directories-first'
alias ee='ls -talhv --group-directories-first'
alias fman='compgen -c | fzf | xargs man'
alias lg='lazygit'
alias t='tmux'
alias q='exit'
alias qa='exit'
alias qq='exit'
alias c='xclip -selection clipboard'
alias y='xclip -selection clipboard -o'
alias cd='z'
alias gc='git commit'
alias gp='git push'
alias gm='git pull'
export PATH=$PATH:~/go/bin
export PATH=$PATH:~/.dotnet/tools
export PATH=$PATH:~/.cargo/bin
export PATH=$PATH:~/.config/emacs/bin
export PATH=$PATH:/usr/sbin/
export PATH=$PATH:~/.local/bin/
eval "$(zoxide init zsh)"
