# DO NOT EDIT. Configuration generated by usc
function l-func {
	ls -l
}
Set-Alias l l-func
function ll-func {
	ls -latrh
}
Set-Alias ll ll-func
function record-func {
	asciinema rec
}
Set-Alias record record-func
function em-func {
	emacs -Q -nw
}
Set-Alias em em-func
function ada-func {
	gnatmake
}
Set-Alias ada ada-func
function vsc-func {
	code .
}
Set-Alias vsc vsc-func
function g-func {
	git
}
Set-Alias g g-func
function ga-func {
	git add -A
}
Set-Alias ga ga-func
function gs-func {
	ga;gc;gp
}
Set-Alias gs gs-func
function gcl-func {
	git clone
}
Set-Alias gcl gcl-func
function n-func {
	npm
}
Set-Alias n n-func
function pn-func {
	pnpm
}
Set-Alias pn pn-func
function e-func {
	ls -t --color=auto --group-directories-first
}
Set-Alias e e-func
function ee-func {
	ls -talhv --group-directories-first
}
Set-Alias ee ee-func
function fman-func {
	compgen -c | fzf | xargs man
}
Set-Alias fman fman-func
function lg-func {
	lazygit
}
Set-Alias lg lg-func
function t-func {
	tmux
}
Set-Alias t t-func
function q-func {
	exit
}
Set-Alias q q-func
function qa-func {
	exit
}
Set-Alias qa qa-func
function qq-func {
	exit
}
Set-Alias qq qq-func
function pt-func {
	powertoys
}
Set-Alias pt pt-func
